service: my-service

provider:
  name: aws
  runtime: python3.8
  stage: prod
  profile: your-aws-profile

plugins:
  - serverless-localstack

custom:
  localstack:
    stages:
      - local
    host: http://localhost
    edgePort: 4566
    autostart: true # If starting localstack manually, set this to false
    lambda:
      mountCode: true # If starting localstack manually, set this to false
      docker:
        sudo: false

functions:
  hello:
    handler: handler.hello
    events:
      - http: POST hello
